[[xkbcommon]]
arch = "armv7l"
git-tree-sha1 = "9a3a5476e8608d8162d2dc782ac2356127e9517e"
libc = "glibc"
os = "linux"

    [[xkbcommon.download]]
    sha256 = "2b6195a1bfedc787b52cabea98c4d6f1d7f6ae2ca5db9e4ae1f9cb3e03aed350"
    url = "https://github.com/JuliaBinaryWrappers/xkbcommon_jll.jl/releases/download/xkbcommon-v0.9.1+0/xkbcommon.v0.9.1.arm-linux-gnueabihf.tar.gz"
[[xkbcommon]]
arch = "aarch64"
git-tree-sha1 = "568e5ebd1df26f3441e4b82c87ad7247630e7f95"
libc = "musl"
os = "linux"

    [[xkbcommon.download]]
    sha256 = "cb99da3507da75d5420555b6368416ec176d7703eb46c00da21bfe6a6fcf520a"
    url = "https://github.com/JuliaBinaryWrappers/xkbcommon_jll.jl/releases/download/xkbcommon-v0.9.1+0/xkbcommon.v0.9.1.aarch64-linux-musl.tar.gz"
[[xkbcommon]]
arch = "i686"
git-tree-sha1 = "83d9baa63b779e64e96bf349e5cbf0ba60fa7453"
libc = "musl"
os = "linux"

    [[xkbcommon.download]]
    sha256 = "1540fb957587f45b3a9114c80a188edafbe7f77a226dfac4e489c5e261339e17"
    url = "https://github.com/JuliaBinaryWrappers/xkbcommon_jll.jl/releases/download/xkbcommon-v0.9.1+0/xkbcommon.v0.9.1.i686-linux-musl.tar.gz"
[[xkbcommon]]
arch = "i686"
git-tree-sha1 = "1095eb613f3b88ab8890675b37cecd865568a526"
libc = "glibc"
os = "linux"

    [[xkbcommon.download]]
    sha256 = "26ff117ce496b931c9ed9a6d00c18bd09473aa1a283b59cc7f703f8c5fee7111"
    url = "https://github.com/JuliaBinaryWrappers/xkbcommon_jll.jl/releases/download/xkbcommon-v0.9.1+0/xkbcommon.v0.9.1.i686-linux-gnu.tar.gz"
[[xkbcommon]]
arch = "powerpc64le"
git-tree-sha1 = "afe581c4ccb33308099ff7d0970d95b302b942bf"
libc = "glibc"
os = "linux"

    [[xkbcommon.download]]
    sha256 = "dcea1f1adae767f424f0920091149820d8e989f9483082a919be6e43a701286f"
    url = "https://github.com/JuliaBinaryWrappers/xkbcommon_jll.jl/releases/download/xkbcommon-v0.9.1+0/xkbcommon.v0.9.1.powerpc64le-linux-gnu.tar.gz"
[[xkbcommon]]
arch = "armv7l"
git-tree-sha1 = "54bef8a0635af408f0156ca44cc1b79ac823acfd"
libc = "musl"
os = "linux"

    [[xkbcommon.download]]
    sha256 = "4f21d1a6900b34fc17ffa192533ef0540030c347f6e83b6ff577c9c78e41f985"
    url = "https://github.com/JuliaBinaryWrappers/xkbcommon_jll.jl/releases/download/xkbcommon-v0.9.1+0/xkbcommon.v0.9.1.arm-linux-musleabihf.tar.gz"
[[xkbcommon]]
arch = "aarch64"
git-tree-sha1 = "fb15ed5e8591f42be519e3db10c9ae1649cb38ee"
libc = "glibc"
os = "linux"

    [[xkbcommon.download]]
    sha256 = "7cb9c28390ff9abc3a0e8a02a91511fa2a7f30e904fb59b66c9bce7be0ad374a"
    url = "https://github.com/JuliaBinaryWrappers/xkbcommon_jll.jl/releases/download/xkbcommon-v0.9.1+0/xkbcommon.v0.9.1.aarch64-linux-gnu.tar.gz"
[[xkbcommon]]
arch = "x86_64"
git-tree-sha1 = "5fe5411a0c16b8252773949dc4f15ebbb1c5640d"
libc = "glibc"
os = "linux"

    [[xkbcommon.download]]
    sha256 = "50ded8240dfca45bff01d5b61957d4622904409c0684545f1f73649969a509a7"
    url = "https://github.com/JuliaBinaryWrappers/xkbcommon_jll.jl/releases/download/xkbcommon-v0.9.1+0/xkbcommon.v0.9.1.x86_64-linux-gnu.tar.gz"
[[xkbcommon]]
arch = "x86_64"
git-tree-sha1 = "d0c916ee3c81f86775eba565af0705c0975b0d5a"
libc = "musl"
os = "linux"

    [[xkbcommon.download]]
    sha256 = "c51849b80d18f23f4339ab2d4e1635f7693cbc38346c6170fd5cd68cf8375ade"
    url = "https://github.com/JuliaBinaryWrappers/xkbcommon_jll.jl/releases/download/xkbcommon-v0.9.1+0/xkbcommon.v0.9.1.x86_64-linux-musl.tar.gz"
